# This file was generated by GoReleaser. DO NOT EDIT.
class Vcsinfo < Formula
  desc "A tool for retrieving/displaying basic information about the status of a VCS repository."
  homepage "https://github.com/jayclassless/vcsinfo"
  url "https://github.com/jayclassless/vcsinfo/releases/download/0.1.3/vcsinfo_0.1.3_macos_amd64.tar.gz"
  version "0.1.3"
  sha256 "a1c6e3b5ae8da916face776fff43634da90a453f7fb9f077222409ed35240ea1"

  def install
    bin.install "vcsinfo"
  end
end
